[package]
name = "stock_parser"
version = "0.1.0"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
stock_span = { workspace = true }
stock_lexer = { workspace = true }
stock_ast = { workspace = true }
